name: Kittygram CI/CD

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
          POSTGRES_DB: kittygram_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U kittygram_user -d kittygram_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip "setuptools<70" wheel
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r backend/requirements.txt

      - name: Lint backend (flake8)
        run: |
          cd backend
          flake8

      - name: Run backend tests
        env:
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
          POSTGRES_DB: kittygram_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          cd backend
          python manage.py test

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Frontend tests
        run: |
          cd frontend
          npm ci
          npm test -- --watchAll=false

  build_and_push:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: egor323011/kittygram_backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: egor323011/kittygram_frontend:latest

      - name: Build and push gateway
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: egor323011/kittygram_gateway:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/kittygram
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml up -d

            docker compose -f docker-compose.production.yml exec -T backend python manage.py migrate
            docker compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput

  send_message:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!